Дипломный проект, основная часть
alex-pergushev/java-explore-with-me pull request #1
Opened 2022-11-11 05:56 UTC by alex-pergushev

2022-11-16 10:42 UTC, kukolev requested changes

2022-11-16 10:42 UTC, kukolev commented on main-server/src/main/java/ru/practicum/ewm/entities/Compilation.java
> +    private String title;
Это поле лучше тоже отметить как `@Column`, т.к. явное лучше чем неявное. Так код будет восприниматься проще.

Аналогично нужно доработать и остальные поля здесь и в других сущностях, где нет `@Column`

2022-11-16 10:42 UTC, kukolev commented on main-server/src/main/java/ru/practicum/ewm/enums/SortingEvents.java
> +    EVENT_DATE("EVENT_DATE"),
Здесь нет смысла добавлять поле sort, т.к. значения поля всегда совпадает с элементом енума. Можно просто использовать EVENT_DATE.name(), вместо ENUM_DATE.getSort().

Аналогично нужно поправить и в других енумах.

2022-11-16 10:42 UTC, kukolev commented on main-server/src/main/java/ru/practicum/ewm/services/EventPersonalServiceImpl.java
> +        Event event = eventRepository.findByIdAndInitiatorId(eventId, userId)
Этот код повторяется три раза и содержит логику обработки ошибок. Такой код нужно вынести в отдельный метод и переиспользовать.

2022-11-16 10:42 UTC, kukolev commented on main-server/src/main/java/ru/practicum/ewm/services/EventPersonalServiceImpl.java
> +        if (!eventRepository.existsByIdAndInitiatorId(eventId, userId))
Этот код повторяется два раза и содержит логику обработки ошибок. Такой код нужно вынести в отдельный метод и переиспользовать.

2022-11-16 10:42 UTC, kukolev commented on main-server/src/test/java/ru/practicum/ewm/dtos/CategoryChangedDtoTest.java
> +    JacksonTester<CategoryChangedDto> json;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-11-16 10:42 UTC, kukolev commented on main-server/src/test/java/ru/practicum/ewm/dtos/CategoryInDtoTest.java
> +    JacksonTester<CategoryInDto> json;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-11-16 10:42 UTC, kukolev commented on main-server/src/test/java/ru/practicum/ewm/dtos/CategoryOutDtoTest.java
> +    JacksonTester<CategoryOutDto> json;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-11-16 10:42 UTC, kukolev commented on main-server/src/main/resources/schema.sql
> +    state VARCHAR(64) NOT NULL DEFAULT 'PENDING',
Слишком большой размер для поля енума. Размер не должен превышать максимальную длину самого длинного элемента енума.

2022-11-16 10:42 UTC, kukolev commented on main-server/src/main/resources/schema.sql
> +    status VARCHAR(64) NOT NULL DEFAULT 'PENDING',
Слишком большой размер для поля енума. Размер не должен превышать максимальную длину самого длинного элемента енума.

2022-11-16 13:34 UTC, alex-pergushev commented on main-server/src/main/java/ru/practicum/ewm/entities/Compilation.java
> +    private String title;
Done

2022-11-16 13:36 UTC, alex-pergushev commented on main-server/src/test/java/ru/practicum/ewm/dtos/CategoryChangedDtoTest.java
> +    JacksonTester<CategoryChangedDto> json;
Done

2022-11-16 13:37 UTC, alex-pergushev commented on main-server/src/test/java/ru/practicum/ewm/dtos/CategoryInDtoTest.java
> +    JacksonTester<CategoryInDto> json;
Done

2022-11-16 13:37 UTC, alex-pergushev commented on main-server/src/test/java/ru/practicum/ewm/dtos/CategoryOutDtoTest.java
> +    JacksonTester<CategoryOutDto> json;
Done

2022-11-16 13:40 UTC, alex-pergushev commented on main-server/src/main/resources/schema.sql
> +    state VARCHAR(64) NOT NULL DEFAULT 'PENDING',
Done

2022-11-16 14:01 UTC, alex-pergushev commented on main-server/src/main/java/ru/practicum/ewm/services/EventPersonalServiceImpl.java
> +        Event event = eventRepository.findByIdAndInitiatorId(eventId, userId)
Done

2022-11-16 14:13 UTC, alex-pergushev commented on main-server/src/main/java/ru/practicum/ewm/services/EventPersonalServiceImpl.java
> +        if (!eventRepository.existsByIdAndInitiatorId(eventId, userId))
Done

2022-11-16 15:09 UTC, alex-pergushev commented on main-server/src/main/java/ru/practicum/ewm/enums/SortingEvents.java
> +    EVENT_DATE("EVENT_DATE"),
Done

2022-11-17 17:03 UTC, kukolev approved these changes

2022-11-17 18:09 UTC, merged